### ISSUE TITLE
Missing data & data inconsistency

### ISSUE THREAD

**Issue by matxx** [cheahjs/bravefrontier_data#46]
Dunno if you keep track of those but there are some unknown proc ids, I've made up a little sum up

```
# GLobal

adds probablity to perform 1 extra action within the same turn
"unknown proc id": "76",
"unknown proc param": "1,50,1,0" (850368 Gaston)
"unknown proc param": "1,50,1,0" (810177 Mai Shiranui)

boosts own Spark damage for 3 turns
"unknown proc id": "88",
"unknown proc param": "30,0,0,0,0,0,3,0" (810417 Rogue Inquisitor Adriesta)
"unknown proc param": "10,0,0,0,0,0,3,110" (10916 Wicked Warrior Shura)

fills own BB gauge to max
"unknown proc id": "90",
"unknown proc param": "999,1,0" (860186 Omega Rugal)

negates critical damage
"unknown proc id": "93",
"unknown proc param": "100,100,0,0,0,0,1,100" (830178 Terry Bogard)
"unknown proc param": "100,100,100,100,0,0,1,170" (20876 Ocean Slasher Holia)
"unknown proc param": "0,0,100,100,0,0,1,110" (30816 Emerald Knight Hisui)

normal attacks hit all foes for 3 turns
"unknown proc id": "94",
"unknown proc param": "0,100,3,0" (850367 Gaston)
"unknown proc param": "0,100,3,110" (20805 Ice Melody Soleil)

# Europe

720154 Gazolina Spray
Cast a mana bubble shielding all allies based on Rec (40%)
"unknown proc id": "70001",
"unknown proc param": "40,30" => 40% REC in shield but 30 what ..
(this type of shield is supposed to not have DEF & not take mitigation into account)
```

Could you please give me your input on this please: 
- seems like Gumi EU has failed the configuration of one exclusive unit
- Pisces of Tyranny's SBB has only one text entry for 2 effects and dot percentage doesn't correspond

Is there something wrong with your parser ? (I doubt it) or have they fucked up ?

```
720176 Pisces of Tyranny SBB
Attack at end of turn 3 turns (300%)
{
    "effect delay time(ms)/frame": "0.0/0",
    "target area": "aoe",
    "target type": "enemy",
    "unknown proc id": "",
    "unknown proc param": "300,100,0,100,1,3,0"
},
{
    "dot atk%": 2,
    "dot dmg%": 3,
    "dot element affected": true,
    "dot flat atk": 15,
    "dot turns (71)": 15,
    "dot unit index": 4,
    "effect delay time(ms)/frame": "0.0/0",
    "proc id": "44",
    "target area": "aoe",
    "target type": "party"
},
```

**Comment by Deathmax** [comment]
Thanks for compiling the unknown procs, will find time to implement them into the parser.

Regarding Pisces of Tyranny's SBB, here is the raw skill level data:

    Kn51uR4Y: "1:2500:2,6,0,440,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0|2:2500:2,6,0,450,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0|3:2500:2,6,0,460,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0|4:2500:2,6,0,470,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0|5:2500:2,6,0,480,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0|6:2500:2,6,0,490,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0|7:2500:2,6,0,500,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0|8:2500:2,6,0,510,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0|9:2500:2,6,0,520,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0|10:2500:2,6,0,540,100,0,0,0,0@1,2,3,4,5,6,0,0@100,100,100,100,100,100,3,0@400,500,100,3,0@300,100,0,100,1,3,0@2,15,3,15,4,15,0,0,3,0@1,10,5,10,6,10,0,0,3,0"

and the following is the proc id raw data:

    hjAy9St3: "29@10@17@20@@44@40@40",

Taking the level 10 SBB data and combining it with the corresponding proc ids:

* **29**: 10:2500:2,6,0,540,100,0,0,0,0
* **10**: 1,2,3,4,5,6,0,0
* **17**: 100,100,100,100,100,100,3,0
* **20**: 400,500,100,3,0
* **??**: 300,100,0,100,1,3,0
* **44**: 2,15,3,15,4,15,0,0,3,0
* **40**: 1,10,5,10,6,10,0,0,3,0
* **40**: Missing

There is an extra @ character in the proc id list, so the data for DoT is coming from the status ailment stuff. If the game ignores empty strings when splitting, then my parser is at fault, else if the game behaves as per the parsed data, then gumi EU have messed up the data.

**Comment by touchandswipe** [comment]
if you need help, shout out mate :) happy to assist.
